require'nvim-treesitter.configs'.setup{
    ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
    ignore_install =                 -- List of parsers to ignore installing
    {
        -- "bash",
        "beancount",
        "bibtex",
        -- "c",
        "c_sharp",
        "clojure",
        -- "cmake",
        -- "comment",
        "commonlisp",
        "cpp",
        "css",
        "cuda",
        "dart",
        "devicetree",
        "dockerfile",
        "elixir",
        "elm",
        "erlang",
        "fennel",
        "fish",
        "fortran",
        "Godot",
        "glimmer",
        "ember",
        "go",
        "Godot Resources",
        "gomod",
        "graphql",
        "haskell",
        "hcl",
        "html",
        "java",
        "javascript",
        "jsdoc",
        "json",
        "jsonc",
        "julia",
        "kotlin",
        "latex",
        "ledger",
        -- "lua",
        "nix",
        "ocaml",
        "ocaml_interface",
        "ocamllex",
        "php",
        -- "python",
        "ql",
        "query",
        "r",
        -- "regex",
        "rst",
        "ruby",
        "rust",
        "scala",
        "scss",
        "sparql",
        "supercollider",
        "surface",
        "svelte",
        "swift",
        "teal",
        "toml",
        "tsx",
        "turtle",
        "typescript",
        "verilog",
        "vim",
        "vue",
        "yaml",
        "yang",
        "zig",
    },

    highlight =
    {
      enable = false, disable = {},
      additional_vim_regex_highlighting = false,
    },

    incremental_selection =
    {
        enable = true,
        keymaps =
        {
            init_selection = "vv",
            node_decremental = "ve",
            node_incremental = "vn",
            -- scope_incremental = "vt"
        },
    },
}
